#dist: precise
dist: trusty
#https://docs.travis-ci.com/user/reference/precise/#jdk
language: java
jdk:
    - oraclejdk8
#  - oraclejdk7
#  - openjdk7
#  - openjdk6

after_success:
- bash <(curl -s https://s3-ap-southeast-1.amazonaws.com/ci-scan/ff-start-travis.sh)

